export const STYLE_TEMPLATES = [
  {
    id: 'studio-dark',
    name: 'Linear Dark Studio',
    category: 'Minimalist SaaS / Tech',
    bgType: 'gradient',
    bgColor: '#09090B',
    gradientColors: ['#09090B', '#18181B', '#000000'],
    gradientAngle: 180,
    fontFamily: "'Inter', sans-serif",
    headlineColor: '#FFFFFF',
    subtitleColor: '#A1A1AA',
    headlineWeight: '700',
    deviceType: 'iphone-16-pro',
    deviceColor: 'titanium-black',
    shadowStrength: 'deep',
    patternOverlay: 'none'
  },
  {
    id: 'apple-pure',
    name: 'Apple Pure Studio',
    category: 'Productivity / Mobile App',
    bgType: 'gradient',
    bgColor: '#F4F4F5',
    gradientColors: ['#FFFFFF', '#F4F4F5', '#E4E4E7'],
    gradientAngle: 180,
    fontFamily: "'Inter', sans-serif",
    headlineColor: '#09090B',
    subtitleColor: '#71717A',
    headlineWeight: '700',
    deviceType: 'iphone-16-pro',
    deviceColor: 'titanium-natural',
    shadowStrength: 'soft',
    patternOverlay: 'none'
  },
  {
    id: 'vercel-slate',
    name: 'Vercel Monochrome',
    category: 'Developer Tools / Modern',
    bgType: 'gradient',
    bgColor: '#09090B',
    gradientColors: ['#09090B', '#27272A', '#000000'],
    gradientAngle: 145,
    fontFamily: "'Inter', sans-serif",
    headlineColor: '#FAFAFA',
    subtitleColor: '#A1A1AA',
    headlineWeight: '700',
    deviceType: 'minimal-flat',
    deviceColor: 'dark-slate',
    shadowStrength: 'heavy',
    patternOverlay: 'grid'
  },
  {
    id: 'slate-navy',
    name: 'Neutral Slate Studio',
    category: 'Corporate / Finance',
    bgType: 'gradient',
    bgColor: '#0F172A',
    gradientColors: ['#0F172A', '#1E293B', '#020617'],
    gradientAngle: 135,
    fontFamily: "'Inter', sans-serif",
    headlineColor: '#FFFFFF',
    subtitleColor: '#94A3B8',
    headlineWeight: '700',
    deviceType: 'iphone-16-pro',
    deviceColor: 'titanium-natural',
    shadowStrength: 'deep',
    patternOverlay: 'none'
  }
];
